import { FormField, ProgramSettings, WhatsAppSettings, Application, AdminUser, AuditLog } from '../types';

export const STATUS_CONFIG: Record<
  string,
  { label: string; badgeClass: string; color: string; description: string; stepIndex: number }
> = {
  SUBMITTED: {
    label: 'Submitted',
    badgeClass: 'badge-submitted',
    color: '#1d4ed8',
    description: 'Your application has been received and logged in the queue.',
    stepIndex: 1,
  },
  UNDER_REVIEW: {
    label: 'Under Review',
    badgeClass: 'badge-under_review',
    color: '#a16207',
    description: 'Your application is currently being evaluated by the case committee.',
    stepIndex: 2,
  },
  ADDITIONAL_INFO_REQUIRED: {
    label: 'Additional Info Required',
    badgeClass: 'badge-additional_info_required',
    color: '#c2410c',
    description: 'Further supporting verification or clarification has been requested.',
    stepIndex: 2,
  },
  APPROVED: {
    label: 'Approved',
    badgeClass: 'badge-approved',
    color: '#15803d',
    description: 'Your application meets all eligibility requirements and has been approved.',
    stepIndex: 3,
  },
  REJECTED: {
    label: 'Rejected',
    badgeClass: 'badge-rejected',
    color: '#b91c1c',
    description: 'Application was not selected in this grant allocation cycle.',
    stepIndex: 3,
  },
  COMPLETED: {
    label: 'Completed',
    badgeClass: 'badge-completed',
    color: '#7e22ce',
    description: 'All disbursement or onboarding formalities are fully finalized.',
    stepIndex: 4,
  },
};

export const DEFAULT_PROGRAM_SETTINGS: ProgramSettings = {
  orgName: 'احساس پبلک ویلفیئر و قومی امداد پورٹل (Ehsaas Relief)',
  programName: 'احساس 10,000 روپے نقد امداد و 50GB مفت انٹرنیٹ ریلیف پیکیج 2026',
  grantAmountText: 'Rs. 10,000 / PKR 10,000',
  description: 'حکومتِ پاکستان پبلک ویلفیئر اور احساس پروگرام کے تحت مستحق شہریوں کو 10,000 روپے نقد امداد اور 50GB مفت 4G ڈیٹا کی براہ راست فراہمی۔ رقم ایزی پیسہ، جاز کیش یا بینک اکاؤنٹ میں براہ راست منتقل کی جاتی ہے۔',
  logoText: 'احساس ریلیف (Ehsaas Relief)',
  contactEmail: 'support@ehsasreliefprogram.vercel.app',
  contactPhone: '0800-24624',
  website: 'https://ehsasreliefprogram.vercel.app',
  instructions: 'Please provide accurate CNIC, contact, and account details. If approved, Rs. 10,000 grant funds will be transferred directly to your Easypaisa/JazzCash/Bank account and an SMS confirmation will be sent. 100% free of charge.',
  privacyNotice: 'Your CNIC and account details are encrypted and processed strictly for applicant identification and direct financial disbursement.',
  termsText: 'By submitting this application, you declare that your provided account details are active and accurate. Funds are dispatched directly upon case approval.',
  footerText: 'احساس قومی ریلیف پورٹل 2026 • Ehsaas Qaumi Relief Program',
  primaryCtaText: 'ابھی 10,000 روپے کے لیے اپلائی کریں',
  adsenseEnabled: true,
  adsenseClientId: 'ca-pub-0000000000000000',
  adsenseHeaderSlotId: '1234567890',
  adsenseInArticleSlotId: '0987654321',
};

export const DEFAULT_WHATSAPP_SETTINGS: WhatsAppSettings = {
  enabled: true,
  campaignUrl: 'https://ehsasreliefprogram.vercel.app/apply',
  grantAmountText: 'Rs. 10,000',
  shareMessageTemplate: 'السلام علیکم! 📢 احساس قومی ریلیف پورٹل کی طرف سے تمام مستحق شہریوں اور طلبہ کے لیے {GRANT_AMOUNT} نقد امداد اور 50GB مفت ڈیٹا پیکیج کا اعلان کیا گیا ہے۔ اپنا شناختی کارڈ اور ایزی پیسہ/جاز کیش اکاؤنٹ درج کر کے ابھی حاصل کریں: {URL}',
  groupShareMessageTemplate: '📢 ضروری اطلاع: احساس پبلک ریلیف پروگرام کے تحت {GRANT_AMOUNT} کیش گرانٹ اور 50GB ڈیٹا کی رجسٹریشن جاری ہے۔ محدود کوٹہ ہے، ابھی آن لائن اپلائی کریں: {URL}',
  targetContactsCount: 10,
  targetGroupsCount: 1,
  buttonText: 'Share on WhatsApp',
  descriptionText: 'Share with 10 contacts and 1 WhatsApp group to unlock 100% meter and complete application eligibility criteria.',
  helplineNumber: '0800-24624',
};

export const DEFAULT_FORM_FIELDS: FormField[] = [
  {
    id: 'f-name',
    name: 'fullName',
    label: 'Full Name (پورا نام)',
    placeholder: 'e.g. Muhammad Ali / Sarah Khan',
    type: 'text',
    section: 'personal',
    required: true,
    order: 1,
    isActive: true,
    hint: 'Enter your full official name as per CNIC / ID',
  },
  {
    id: 'f-cnic',
    name: 'nationalId',
    label: 'CNIC / National ID (شناختی کارڈ نمبر)',
    placeholder: 'e.g. 42101-1234567-8',
    type: 'text',
    section: 'personal',
    required: true,
    order: 2,
    isActive: true,
    hint: '13-digit CNIC or National ID number',
  },
  {
    id: 'f-phone',
    name: 'phone',
    label: 'Phone Number (موبائل فون نمبر)',
    placeholder: 'e.g. 0300-1234567 or +92 300 1234567',
    type: 'phone',
    section: 'personal',
    required: true,
    order: 3,
    isActive: true,
    hint: 'Primary contact phone number',
  },
  {
    id: 'f-whatsapp',
    name: 'whatsappNumber',
    label: 'WhatsApp Number (واٹس ایپ نمبر)',
    placeholder: 'e.g. 0300-1234567 or +92 300 1234567',
    type: 'phone',
    section: 'personal',
    required: true,
    order: 4,
    isActive: true,
    hint: 'Active WhatsApp number for verification and updates',
  },
  {
    id: 'f-address',
    name: 'address',
    label: 'Complete Address & City (مکمل پتہ اور شہر)',
    placeholder: 'e.g. House # 12, Street 4, Sector G-10, Islamabad / Lahore / Karachi',
    type: 'textarea',
    section: 'address',
    required: true,
    order: 5,
    isActive: true,
    hint: 'House/Street, Area, and City name',
  },
];

export const INITIAL_DEMO_APPLICATIONS: Application[] = [
  {
    applicationId: 'APP-2026-000101',
    personalInfo: {
      fullName: 'Amina Khatun',
      guardianName: 'Rashid Ali',
      dateOfBirth: '1992-04-14',
      gender: 'Female',
      nationalId: 'ID-35202-984321',
      phone: '+1 (555) 432-8812',
      whatsappNumber: '+1 (555) 432-8812',
      email: 'amina.khatun@demo-mail.com',
    },
    addressInfo: {
      province: 'Central Province',
      district: 'West Valley District',
      city: 'Greenwood',
      area: 'Block 4, Gulshan Area',
      address: 'House 14-B, Lane 3, near Community Health Clinic',
    },
    householdInfo: {
      familyMembers: 6,
      dependents: 4,
      employmentStatus: 'Informal / Self-Employed',
      monthlyIncome: 320,
      housingStatus: 'Rented Accomodation',
    },
    reasonForApplication: 'Requesting vocational sewing machine kit and emergency sustenance grant to support 4 school-going children following family income disruption.',
    additionalInfo: 'Referred by Local Neighborhood Women Welfare Committee.',
    customFields: {},
    submissionDate: new Date(Date.now() - 6 * 86400000).toISOString(),
    currentStatus: 'APPROVED',
    lastUpdated: new Date(Date.now() - 1 * 86400000).toISOString(),
    statusHistory: [
      {
        status: 'SUBMITTED',
        timestamp: new Date(Date.now() - 6 * 86400000).toISOString(),
        changedBy: 'System (Public Form)',
      },
      {
        status: 'UNDER_REVIEW',
        timestamp: new Date(Date.now() - 4 * 86400000).toISOString(),
        changedBy: 'Review Officer (admin@ehsasreliefprogram.vercel.app)',
        note: 'Income certificate and rental agreement verified.',
      },
      {
        status: 'APPROVED',
        timestamp: new Date(Date.now() - 1 * 86400000).toISOString(),
        changedBy: 'Super Admin',
        note: 'Approved for Category A vocational grant.',
      },
    ],
    notes: [
      {
        id: 'note-1',
        author: 'Sarah Admin',
        timestamp: new Date(Date.now() - 3 * 86400000).toISOString(),
        text: 'Conducted field telephone verification with community leader. Verified applicant household status.',
      },
    ],
    outreachHistory: [
      {
        id: 'share-101',
        applicationId: 'APP-2026-000101',
        placement: 'submission_success',
        timestamp: new Date(Date.now() - 6 * 86400000).toISOString(),
        sessionId: 'sess_99182',
        userAgent: 'Mozilla/5.0 (Mobile)',
      },
    ],
  },
  {
    applicationId: 'APP-2026-000102',
    personalInfo: {
      fullName: 'Marcus Vance',
      guardianName: 'Arthur Vance',
      dateOfBirth: '1988-11-20',
      gender: 'Male',
      nationalId: 'ID-41029-441980',
      phone: '+1 (555) 789-2244',
      whatsappNumber: '+1 (555) 789-2244',
      email: 'm.vance88@demo-mail.com',
    },
    addressInfo: {
      province: 'Eastern Region',
      district: 'North River County',
      city: 'Metroville',
      area: 'Industrial Ward 9',
      address: 'Apartment 302, Sunrise Heights, Old Depot Road',
    },
    householdInfo: {
      familyMembers: 4,
      dependents: 2,
      employmentStatus: 'Daily Wage Worker',
      monthlyIncome: 280,
      housingStatus: 'Rented Accomodation',
    },
    reasonForApplication: 'Applying for small artisan tool micro-grant to re-establish home repair service after workshop fire.',
    additionalInfo: '',
    customFields: {},
    submissionDate: new Date(Date.now() - 4 * 86400000).toISOString(),
    currentStatus: 'UNDER_REVIEW',
    lastUpdated: new Date(Date.now() - 2 * 86400000).toISOString(),
    statusHistory: [
      {
        status: 'SUBMITTED',
        timestamp: new Date(Date.now() - 4 * 86400000).toISOString(),
        changedBy: 'System (Public Form)',
      },
      {
        status: 'UNDER_REVIEW',
        timestamp: new Date(Date.now() - 2 * 86400000).toISOString(),
        changedBy: 'Review Officer (admin@ehsasreliefprogram.vercel.app)',
        note: 'Assigned to technical assessment officer.',
      },
    ],
    notes: [],
    outreachHistory: [],
  },
  {
    applicationId: 'APP-2026-000103',
    personalInfo: {
      fullName: 'Fatima Zahra',
      guardianName: 'Qasim Zahra',
      dateOfBirth: '1995-07-03',
      gender: 'Female',
      nationalId: 'ID-55100-332190',
      phone: '+1 (555) 601-3312',
      whatsappNumber: '+1 (555) 601-3312',
      email: 'f.zahra@demo-mail.com',
    },
    addressInfo: {
      province: 'Southern Coast',
      district: 'Harbor District',
      city: 'Seaport City',
      area: 'Fisherman Colony',
      address: 'House 88, Coastal Row 2',
    },
    householdInfo: {
      familyMembers: 7,
      dependents: 5,
      employmentStatus: 'Unemployed / Seeking Work',
      monthlyIncome: 190,
      housingStatus: 'Informal / Temporary Shelter',
    },
    reasonForApplication: 'Immediate nutritional and basic living support following seasonal employment halt.',
    additionalInfo: 'Family has two elderly members requiring medical supplies.',
    customFields: {},
    submissionDate: new Date(Date.now() - 2 * 86400000).toISOString(),
    currentStatus: 'ADDITIONAL_INFO_REQUIRED',
    lastUpdated: new Date(Date.now() - 1 * 86400000).toISOString(),
    statusHistory: [
      {
        status: 'SUBMITTED',
        timestamp: new Date(Date.now() - 2 * 86400000).toISOString(),
        changedBy: 'System (Public Form)',
      },
      {
        status: 'ADDITIONAL_INFO_REQUIRED',
        timestamp: new Date(Date.now() - 1 * 86400000).toISOString(),
        changedBy: 'Case Reviewer',
        note: 'Please provide updated utility or residency confirmation letter.',
      },
    ],
    notes: [
      {
        id: 'note-2',
        author: 'Case Reviewer',
        timestamp: new Date(Date.now() - 1 * 86400000).toISOString(),
        text: 'Contacted via WhatsApp requesting clear scan of local residency card.',
      },
    ],
    outreachHistory: [
      {
        id: 'share-103',
        applicationId: 'APP-2026-000103',
        placement: 'submission_success',
        timestamp: new Date(Date.now() - 2 * 86400000).toISOString(),
        sessionId: 'sess_44123',
        userAgent: 'Mozilla/5.0 (iPhone; CPU iPhone OS 17_0)',
      },
    ],
  },
  {
    applicationId: 'APP-2026-000104',
    personalInfo: {
      fullName: 'David Chen',
      guardianName: 'Liang Chen',
      dateOfBirth: '1990-02-18',
      gender: 'Male',
      nationalId: 'ID-99201-118833',
      phone: '+1 (555) 912-7744',
      whatsappNumber: '+1 (555) 912-7744',
      email: 'd.chen@demo-mail.com',
    },
    addressInfo: {
      province: 'Central Province',
      district: 'Highland District',
      city: 'Oakridge',
      area: 'Midtown East',
      address: '24 Elm Street, Apt 4B',
    },
    householdInfo: {
      familyMembers: 3,
      dependents: 1,
      employmentStatus: 'Salaried (Low Income)',
      monthlyIncome: 650,
      housingStatus: 'Rented Accomodation',
    },
    reasonForApplication: 'Applying for vocational tech certification stipend to upskill into digital support roles.',
    additionalInfo: '',
    customFields: {},
    submissionDate: new Date(Date.now() - 1 * 86400000).toISOString(),
    currentStatus: 'SUBMITTED',
    lastUpdated: new Date(Date.now() - 1 * 86400000).toISOString(),
    statusHistory: [
      {
        status: 'SUBMITTED',
        timestamp: new Date(Date.now() - 1 * 86400000).toISOString(),
        changedBy: 'System (Public Form)',
      },
    ],
    notes: [],
    outreachHistory: [],
  },
  {
    applicationId: 'APP-2026-000105',
    personalInfo: {
      fullName: 'Zainab Bibi',
      guardianName: 'Muhammad Ismail',
      dateOfBirth: '1984-09-12',
      gender: 'Female',
      nationalId: 'ID-31102-772910',
      phone: '+1 (555) 231-9988',
      whatsappNumber: '+1 (555) 231-9988',
      email: 'zainab.b@demo-mail.com',
    },
    addressInfo: {
      province: 'Western Province',
      district: 'River Valley District',
      city: 'Riverside',
      area: 'Bazaar Colony',
      address: 'Shop 4-Rear, Main Market Road',
    },
    householdInfo: {
      familyMembers: 5,
      dependents: 3,
      employmentStatus: 'Disabled / Unable to Work',
      monthlyIncome: 160,
      housingStatus: 'Family Owned (Shared)',
    },
    reasonForApplication: 'Special disability allowance and household food security package.',
    additionalInfo: 'Medical disability certificate attached.',
    customFields: {},
    submissionDate: new Date(Date.now() - 10 * 86400000).toISOString(),
    currentStatus: 'COMPLETED',
    lastUpdated: new Date(Date.now() - 2 * 86400000).toISOString(),
    statusHistory: [
      {
        status: 'SUBMITTED',
        timestamp: new Date(Date.now() - 10 * 86400000).toISOString(),
        changedBy: 'System (Public Form)',
      },
      {
        status: 'UNDER_REVIEW',
        timestamp: new Date(Date.now() - 8 * 86400000).toISOString(),
        changedBy: 'Review Officer',
      },
      {
        status: 'APPROVED',
        timestamp: new Date(Date.now() - 5 * 86400000).toISOString(),
        changedBy: 'Super Admin',
      },
      {
        status: 'COMPLETED',
        timestamp: new Date(Date.now() - 2 * 86400000).toISOString(),
        changedBy: 'Disbursement Team',
        note: 'Grant package distributed via partner bank transfer.',
      },
    ],
    notes: [
      {
        id: 'note-5',
        author: 'Disbursement Team',
        timestamp: new Date(Date.now() - 2 * 86400000).toISOString(),
        text: 'Funds transferred successfully. Confirmation receipt acknowledged by applicant via WhatsApp call.',
      },
    ],
    outreachHistory: [
      {
        id: 'share-105',
        applicationId: 'APP-2026-000105',
        placement: 'landing_hero',
        timestamp: new Date(Date.now() - 10 * 86400000).toISOString(),
        sessionId: 'sess_11099',
        userAgent: 'Mozilla/5.0 (Android)',
      },
    ],
  },
];

export const INITIAL_ADMINS: AdminUser[] = [
  {
    id: 'admin-1',
    name: 'Sarah Jenkins',
    email: 'admin@ehsasreliefprogram.vercel.app',
    role: 'Super Admin',
    lastLogin: new Date().toISOString(),
  },
  {
    id: 'admin-2',
    name: 'Tariq Mahmood',
    email: 'reviewer@ehsasreliefprogram.vercel.app',
    role: 'Case Reviewer',
    lastLogin: new Date(Date.now() - 86400000).toISOString(),
  },
];

export const INITIAL_AUDIT_LOGS: AuditLog[] = [
  {
    id: 'audit-1',
    action: 'LOGIN',
    timestamp: new Date(Date.now() - 2 * 3600000).toISOString(),
    details: 'Admin logged into portal from local session.',
    adminEmail: 'admin@ehsasreliefprogram.vercel.app',
    adminName: 'Sarah Jenkins',
  },
  {
    id: 'audit-2',
    action: 'STATUS_CHANGED',
    timestamp: new Date(Date.now() - 1 * 86400000).toISOString(),
    target: 'APP-2026-000101',
    details: 'Status changed from UNDER_REVIEW to APPROVED.',
    adminEmail: 'admin@ehsasreliefprogram.vercel.app',
    adminName: 'Sarah Jenkins',
  },
  {
    id: 'audit-3',
    action: 'NOTE_ADDED',
    timestamp: new Date(Date.now() - 1 * 86400000).toISOString(),
    target: 'APP-2026-000103',
    details: 'Internal case note added requesting residency scan.',
    adminEmail: 'reviewer@ehsasreliefprogram.vercel.app',
    adminName: 'Tariq Mahmood',
  },
];
